#Nombre del programa
MODULE = Prueba

#compilador usado
CC= g++
#Archivos que se compilaran
SRCS = TestBench.cpp main.cpp

#Direccion de systemc
#Nota:la del laboratorio es /home/usuarios/is/arqcomp/systemc
SYSTEMC = /home/usuarios/is/arqcomp/systemc
QSCONNECTION = /home/usuarios/is/arqcomp/systemc/qsconnection
include ./Makefile.defs
