#Nombre del programa
MODULE = Prueba

#compilador usado
CC= g++
#Archivos que se compilaran
SRCS =Adder2Bits.cpp testbench.cpp sc_main.cpp

#Direccion de systemc
#Nota:la del laboratorio es /home/usuarios/is/arqcomp/systemc/systemc-2.2.0
SYSTEMC = /usr/local/lib/systemc-2.2.0

include ./Makefile.defs
